// Copy shared by the mobile and desktop interface.
export const uiEn: Record<string, string> = {
  "ui.letYourFiles": "Let your files,",
  "ui.travelAsLight": "travel as light.",
  "ui.onePhoneLightsUpTheOther":
    "One phone lights up. The other points its camera.",
  "ui.yourPhotosAndFilesTravelBetween":
    "Your photos and files travel between them.",
  "ui.sending": "Sending",
  "ui.receiving": "Receiving",
  "ui.screenToCameraNoUploads": "Screen to camera · No uploads",
  "ui.noNetwork": "No network",
  "ui.noPairing": "No pairing",
  "ui.verifiedFiles": "Verified files",
  "ui.sendAFile": "Send a file",
  "ui.chooseAPhotoOrFile": "Choose a photo or file",
  "ui.receiveAFile": "Receive a file",
  "ui.pointYourCameraAtACode": "Point your camera at a code",
  "ui.openOpticalTransferOnBothDevices":
    "Open Optical Transfer on both devices to begin.",
  "ui.chooseAPhoto": "Choose a photo,",
  "ui.orAFile": "or a file.",
  "ui.sendSomethingWorthSharing": "Send something worth sharing.",
  "ui.photosVideosDocumentsAllWelcome":
    "Photos, videos, documents. All welcome.",
  "ui.haveTheOtherPhone": "Have the other phone",
  "ui.pointHere": "point here.",
  "ui.pointYourCamera": "Point your camera.",
  "ui.catchTheLight": "Catch the light.",
  "ui.yourCameraViewWillAppearHere": "Your camera view will appear here",
  "ui.keepTheEntireCodeInsideThe": "Keep the entire code inside the frame",
  "ui.waitingForAFile": "Waiting for a file",
  "ui.aboutCredits": "About & credits",
  "ui.by": "By",
  "ui.basedOn": "Based on",
  "ui.goToOpticalTransferHome": "Go to Optical Transfer home",
  "ui.navigation": "Navigation",
  "ui.theLeftPhoneDisplaysACode":
    "The left phone displays a code; the right phone receives it with its camera.",
  "ui.codeRecognizedCollectingFileData":
    "Code recognized. Collecting file data.",
  "ui.rxStarting": "Opening camera",
  "ui.rxReady": "Ready to receive",
  "ui.rxSearching": "Searching for a code",
  "ui.rxReceiving": "Receiving",
  "ui.rxWaiting": "Waiting for new data",
  "ui.rxVerifying": "Verifying file",
  "ui.rxComplete": "File verified",
  "ui.rxError": "Please retry",
  "ui.waitHint":
    "No new data right now. Your progress is kept. Hold steady and point at the code again.",
  "ui.txProgress": "{n} frames displayed · actual {fps} fps",
  "ui.txSpecs": "{lanes} code(s) · target {fps} fps · error correction {ecc}",
  "ui.txPaused": "Sending paused",
  "ui.txPausedHint": "Choose resend to start displaying codes again.",
  "ui.pickHint":
    "Defaults suit most phones. Raise the sender’s brightness and keep both devices steady.",
  "ui.progressFrames": "Collected {n} / about {m} frames",
  "ui.verified": "File integrity verified",
  "ui.diagnostics": "Details",
  "ui.statsDetails": "Status & diagnostics",
  "ui.secureNote": "Files travel through the screen, without uploads.",
};

export const uiZh: Record<string, string> = {
  "ui.letYourFiles": "让文件，",
  "ui.travelAsLight": "以光抵达。",
  "ui.onePhoneLightsUpTheOther": "一台手机亮起屏幕，另一台对准镜头。",
  "ui.yourPhotosAndFilesTravelBetween": "照片与文件，就这样传过去。",
  "ui.sending": "发送中",
  "ui.receiving": "接收中",
  "ui.screenToCameraNoUploads": "屏幕对镜头 · 文件无需上传",
  "ui.noNetwork": "无需网络",
  "ui.noPairing": "无需配对",
  "ui.verifiedFiles": "完整校验",
  "ui.sendAFile": "我要发送",
  "ui.chooseAPhotoOrFile": "选择照片或文件",
  "ui.receiveAFile": "我要接收",
  "ui.pointYourCameraAtACode": "用镜头对准光码",
  "ui.openOpticalTransferOnBothDevices":
    "两台设备都打开 Optical Transfer，即可开始。",
  "ui.chooseAPhoto": "选一张照片，",
  "ui.orAFile": "或一份文件。",
  "ui.sendSomethingWorthSharing": "把想分享的，传过去。",
  "ui.photosVideosDocumentsAllWelcome": "照片、视频、文档，都可以。",
  "ui.haveTheOtherPhone": "让另一台手机，",
  "ui.pointHere": "对准这里。",
  "ui.pointYourCamera": "对准屏幕，",
  "ui.catchTheLight": "接住这束光。",
  "ui.yourCameraViewWillAppearHere": "开启后，在这里对准光码",
  "ui.keepTheEntireCodeInsideThe": "让光码完整落在取景框内",
  "ui.waitingForAFile": "等待识别文件",
  "ui.aboutCredits": "关于 Optical Transfer 与致谢",
  "ui.by": "作者",
  "ui.basedOn": "基于",
  "ui.goToOpticalTransferHome": "返回 Optical Transfer 首页",
  "ui.navigation": "切换页面",
  "ui.theLeftPhoneDisplaysACode": "左边的手机显示光码，右边的手机用镜头接收",
  "ui.codeRecognizedCollectingFileData": "光码识别稳定，正在收集文件数据。",
  "ui.rxStarting": "正在开启摄像头",
  "ui.rxReady": "准备接收",
  "ui.rxSearching": "搜索光码",
  "ui.rxReceiving": "正在接收",
  "ui.rxWaiting": "等待新数据",
  "ui.rxVerifying": "正在校验",
  "ui.rxComplete": "校验通过",
  "ui.rxError": "需要重试",
  "ui.waitHint":
    "暂时没有新数据，已收到的进度会保留。请保持设备稳定并重新对准光码。",
  "ui.txProgress": "已显示 {n} 帧 · 实际 {fps} 帧/秒",
  "ui.txSpecs": "显示 {lanes} 个光码 · 目标 {fps} 帧/秒 · 纠错 {ecc}",
  "ui.txPaused": "发送已暂停",
  "ui.txPausedHint": "点击重新发送，让另一台设备继续接收。",
  "ui.pickHint": "默认参数适合大多数手机。发送时提高屏幕亮度，并保持设备稳定。",
  "ui.progressFrames": "已收集 {n} / 约 {m} 帧",
  "ui.verified": "文件完整性校验通过",
  "ui.diagnostics": "详细信息",
  "ui.statsDetails": "运行状态与识别指标",
  "ui.secureNote": "文件通过屏幕传输，无需上传。",
};
